version: "3.8"

services:
  pva:
    build: .
    image: muserpol/pva:1.4
    container_name: pva
    ports:
      - "8181:80"
    volumes:
      # Ajusta esta ruta a donde está tu proyecto en el HOST
      - /PVA:/var/www/html/public
    restart: always